services:
  backend:
    build: ./mock/backend
    command: node server.js
    restart: always
    ports:
      - "8000:3000"
  frontend:
    build: .
    restart: always
    command: npm start --watch --watch-poll
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    stdin_open: true
    depends_on:
      - backend
  nginx:
    image: nginx
    volumes:
      - ./mock/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
