services:
  backend:
    build: ./backend
    image: registry.doit.wisc.edu/cdis/cs/courses/cs506/fa2023/t_16/zigzag/backend:${IMAGE_TAG:-latest}
    restart: always
    volumes:
      - ./backend:/app
    command: sh run_dev.sh
    ports:
      - "8000:8000"
    environment:
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'password'
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - db:/var/lib/mysql
  frontend:
    build: ./frontend
    image: registry.doit.wisc.edu/cdis/cs/courses/cs506/fa2023/t_16/zigzag/frontend:${IMAGE_TAG:-latest}
    restart: always
    command: npm start --watch --watch-poll
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    stdin_open: true
    depends_on:
      - backend
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
  simulation-manager:
    build: ./simserver
    image: registry.doit.wisc.edu/cdis/cs/courses/cs506/fa2023/t_16/zigzag/simulation-manager:${IMAGE_TAG:-latest}
    privileged: true
    restart: always
    stdin_open: true
    ports:
      - 9999:9999
volumes:
  db: { }
