services:
  backend:
    build: ./backend
    restart: always
    command: sh run_prod.sh
    environment:
      DEBUG: "false"
    volumes:
      - media:/media
      - static:/static
    env_file:
      - .env
    depends_on:
      - db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  db:
    image: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  frontend:
    build: ./frontend
    restart: always
    command: serve -s build
    depends_on:
      - backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
      - media:/media
      - static:/static
      - /etc/letsencrypt:/cert
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend
    labels:
      com.centurylinklabs.watchtower.enable: true
      com.centurylinklabs.watchtower.depends-on: "zigzag-frontend-1,zigzag-backend-1"
  simulation-manager:
    build: ./simserver
    privileged: true
    restart: always
    stdin_open: true
volumes:
  db: { }
  media: { }
  static: { }