services:
  backend:
    build: .
    restart: always
    volumes:
      - .:/app
    command: sh run_dev.sh
    ports:
      - "8000:8000"
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - db:/var/lib/mysql
  simulation-manager:
    build: ./mock/simulator
    command: node server.js
    ports:
      - "9000:9999"
  nginx:
    image: nginx
    volumes:
      - ./mock/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - backend
volumes:
  db: { }