# Generated by Django 4.2.5 on 2023-10-10 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0002_rename_end_tournament_stop_and_more"),
        ("maze", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runresult",
            name="maze_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="maze.mazeconfiguration",
            ),
        ),
        migrations.AlterField(
            model_name="runresult",
            name="robot_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="maze.robotconfiguration",
            ),
        ),
        migrations.AlterField(
            model_name="runresult",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tournament.tournament",
            ),
        ),
    ]
