# Generated by Django 4.2.5 on 2023-10-10 20:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maze", "0002_alter_runresult_maze_configuration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="runresult",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
