# Generated by Django 4.2.5 on 2023-10-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maze", "0003_runresult_timestamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="runresult",
            old_name="did_run",
            new_name="did_win",
        ),
        migrations.AlterField(
            model_name="mazeconfiguration",
            name="level_configuration",
            field=models.JSONField(
                help_text="A JSON object representing the rows and columns of the maze"
            ),
        ),
        migrations.AlterField(
            model_name="runresult",
            name="duration",
            field=models.IntegerField(
                help_text="The duration of the robot execution in simulator ticks"
            ),
        ),
        migrations.AlterField(
            model_name="runresult",
            name="result_data",
            field=models.JSONField(
                help_text="JSON data from the simulation with the resulting moves"
            ),
        ),
    ]
