# Generated by Django 4.2.5 on 2023-11-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maze", "0004_rename_did_run_runresult_did_win_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mazeconfiguration",
            name="name",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
