# Generated by Django 4.2.5 on 2023-12-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maze", "0006_snippet_snippet_maze_snippet_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="content",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
