# Generated by Django 4.2.5 on 2023-12-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maze", "0007_snippet_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runresult",
            name="run_error",
            field=models.CharField(max_length=512),
        ),
    ]
