# Generated by Django 4.2.5 on 2023-10-10 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maze", "0001_initial"),
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournament",
            old_name="end",
            new_name="stop",
        ),
        migrations.AddField(
            model_name="tournament",
            name="maze_configuration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="maze.mazeconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="robot_configuration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="maze.robotconfiguration",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="name",
            field=models.CharField(max_length=64),
        ),
    ]
